{
 "title": "UAS Basis Data Terdistribusi",
 "tags": [
  "uas",
  "basis-data-terdistribusi"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Data di Master",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "targets": [
    { "expr": "uts_master_total_rows" }
   ]
  },
  {
   "title": "Total Data Master Visualisasi",
   "type": "timeseries",
   "gridPos": { "x": 6, "y": 0, "w": 18, "h": 8 },
   "targets": [
    { "expr": "uts_master_total_rows" }
   ]
  },
  {
   "title": "Total Data per Shard",
   "type": "bargauge",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    { "expr": "uts_shard_total_rows", "legendFormat": "Shard {{shard_id}}" }
   ]
  },
  {
   "title": "Status Shard (1=hidup, 0=mati)",
   "type": "bargauge",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    { "expr": "uts_shard_up", "legendFormat": "Shard {{shard_id}}" }
   ]
  },
  {
   "title": "Pending Sync",
   "type": "stat",
   "gridPos": { "x": 0, "y": 16, "w": 6, "h": 4 },
   "targets": [
    { "expr": "uts_pending_sync_unsynced" }
   ]
  },
  {
   "title": "Pending Sync Visualisasi",
   "type": "timeseries",
   "gridPos": { "x": 6, "y": 16, "w": 18, "h": 8 },
   "targets": [
    { "expr": "uts_pending_sync_unsynced" }
   ]
  },
  {
   "title": "Log Deteksi Shard",
   "type": "logs",
   "gridPos": { "x": 0, "y": 24, "w": 12, "h": 10 },
   "targets": [
    {
     "expr": "{container=\"utsbtd-watcher\"} |= \"DETEKSI\""
    }
   ]
  },
  {
   "title": "Log Redistribusi",
   "type": "logs",
   "gridPos": { "x": 12, "y": 24, "w": 12, "h": 10 },
   "targets": [
    {
     "expr": "{container=\"utsbtd-watcher\"} |= \"REDISTRIBUSI\""
    }
   ]
  }
 ]
}